import './globals.css'
import { PT_Serif } from 'next/font/google'



const ptSerif = PT_Serif({ subsets: ['latin'], weight: ['400','700'] })

export const metadata = {
  title: ' Enablment Test',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ptSerif.className}>{children}</body>
    </html>
  )
}
